# Generated by Django 2.0.4 on 2018-08-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180821_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posttime',
            new_name='created_on',
        ),
    ]
